pipeline {
    agent any

    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'staging', 'prod'], description: 'Environment to deploy to')
        choice(name: 'ACTION', choices: ['plan', 'apply', 'destroy'], description: 'Terraform action to perform')
    }

    environment {
        TF_IN_AUTOMATION = 'true'
        AWS_REGION        = 'eu-west-2'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                dir('infrastructure/terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            when {
                expression { params.ACTION == 'plan' || params.ACTION == 'apply' }
            }
            steps {
                dir('infrastructure/terraform') {
                    sh "terraform plan -var-file=envs/${params.ENVIRONMENT}.tfvars -out=tfplan"
                }
            }
        }

        stage('Terraform Apply') {
            when {
                expression { params.ACTION == 'apply' }
            }
            steps {
                dir('infrastructure/terraform') {
                    sh "terraform apply -auto-approve tfplan"
                }
            }
        }

        stage('Build Application') {
            when {
                expression { params.ACTION == 'apply' }
            }
            steps {
                dir('app') {
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Deploy Application') {
            when {
                expression { params.ACTION == 'apply' }
            }
            steps {
                dir('infrastructure/ansible') {
                    sh "ansible-playbook -i aws_ec2.yml playbook.yml"
                }
            }
        }

        stage('Terraform Destroy') {
            when {
                expression { params.ACTION == 'destroy' }
            }
            steps {
                dir('infrastructure/terraform') {
                    sh "terraform destroy -var-file=envs/${params.ENVIRONMENT}.tfvars -auto-approve"
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
